const questionPairs = [
  { question: "What would you tell your 10 year old self if you can travel back in time?", questionImposter: "What advice would you give a dog if you could talk to him?" },
  { question: "How many yards do you think you can run after receiving an NFL kickoff?", questionImposter: "How many yards would you want your boat to be long?" },
  { question: "How many dates before kissing?", questionImposter: "Pick a number between 5 and 10." },
  { question: "If you could see any artist in concert who would it be?", questionImposter: "Best concert you've been to?" },
  { question: "How much should you spend on a car?", questionImposter: "How much does a brand new car cost?" },
  { question: "What item in your house you can’t live without?", questionImposter: "What's the most fragile thing in your house." },
  { question: "Best age to start puberty?", questionImposter: "Pick a number from 9 to 15." },
  { question: "What artist do you want to listen more of?", questionImposter: "Which singer sings 'Umbrella'?" },
  { question: "Who is the most responsible in the group (currently playing)?", questionImposter: "Name a person who is currently playing the game." },
  { question: "Who’d you call first if you won the lottery?", questionImposter: "Out of the players currently playing who would you trust the most with a secret?" },
  { question: "How much $ would it take to reveal your Internet search history?", questionImposter: "Pick an amount of money from 1mil to 10mil (round numbers)?" },
  { question: "How many hours of sleep do you get per night", questionImposter: "How would you rate your sleep (1-10)?" },
  { question: "How many alarms do you set to wake up?", questionImposter: "Pick a number between 5 and 15?" },
  { question: "How long could you survive in the woods?", questionImposter: "Pick a time interval (30 days to 1 year, don't be too specific)." },
  { question: "What animal's ability would you want to have?", questionImposter: "What animal are you irrationally afraid of?" },
  { question: "What is the best country to party in?", questionImposter: "Which country would you want to live in?" },
  { question: "Which country has the best cuisine?", questionImposter: "Which country has the worst cuisine?" },
  { question: "Who from the group (currently playing) would make the best lawyer?", questionImposter: "Who from the group (currently playing) would make the best doctor?" },
  { question: "Meme that you quote often?", questionImposter: "Name an Italian brainrot character." },
  { question: "What age did you get your first phone?", questionImposter: "At what age would you let your kid get a phone?" },
  { question: "What celebrity would you like to have a dinner with?", questionImposter: "Most attractive female actor?" },
  { question: "What would you show a medieval peasant?", questionImposter: "What piece of modern technology could you not live without?" },
  { question: "What would you show people from the future to represent 2025?", questionImposter: "Favorite TV show / movie of the year?" },

  { question: "What’s your ideal weekend activity?", questionImposter: "What’s something you usually do on a random Tuesday?" },
  { question: "What food could you eat every day without getting tired of it?", questionImposter: "What food have you eaten recently?" },
  { question: "What hobby would you pick up if you had unlimited free time?", questionImposter: "What hobby did you used to have as a kid?" },
  { question: "What’s your biggest dream in life?", questionImposter: "What’s your least favorite chore at home?" },
  { question: "If you could travel anywhere for free, where would you go?", questionImposter: "Where did you last take a trip?" },
  { question: "What makes you feel most alive?", questionImposter: "What did you do today that was boring?" },
  { question: "What’s a risk you’ve always wanted to take?", questionImposter: "Are you risk-averse or do you like taking chances?" },
  { question: "If you could have dinner with any historical figure, who would it be?", questionImposter: "Who is a famous person you don't like?" },
  { question: "What’s the most embarrassing thing you’ve done?", questionImposter: "What’s a minor awkward moment you remember?" },
  { question: "What hobby would you pick up if you had no limitations?", questionImposter: "What hobby do you wish you had more time for?" },
  { question: "If you won a million dollars today, what’s the first thing you’d do?", questionImposter: "If someone gave you a small bonus, how would you spend it?" },
  { question: "What superpower would you want and why?", questionImposter: "Would you rather be very strong or very fast?" },
  { question: "What’s your favorite memory from childhood?", questionImposter: "What’s a toy you used to have?" },
  { question: "If you could go back in time, what age would you revisit?", questionImposter: "What year were you born again?" },
  { question: "What’s the biggest lesson you’ve learned so far?", questionImposter: "What’s a recent mistake you learned from?" },
  { question: "If you could change one thing about the world, what would it be?", questionImposter: "What’s one thing in your city you’d change?" },
  { question: "What’s a book that changed your perspective?", questionImposter: "What’s a book you tried to read but couldn’t finish?" },
  { question: "What’s something you wish people understood about you?", questionImposter: "What’s one of your bad habits?" },
  { question: "What’s a secret talent you have?", questionImposter: "What’s something you’re not very good at?" },
  { question: "What’s your biggest fear?", questionImposter: "What’s the scariest movie you’ve seen?" },
  { question: "If you could meet your future self, what would you ask?", questionImposter: "What do you hope will happen in the next year?" },
  { question: "What’s something you regret not doing?", questionImposter: "Is there something small you wish you’d done differently?" }
,
  { question: "What would you do if you knew you couldn’t fail?", questionImposter: "What’s the last thing you failed at?" },
  { question: "What are you most grateful for?", questionImposter: "What’s something small that made you happy recently?" },
  { question: "If you could master any instrument, which would you choose?", questionImposter: "Have you ever tried to learn to play an instrument?" },
  { question: "What’s the best piece of advice you’ve ever received?", questionImposter: "What’s advice you often give to others?" },
  { question: "What’s one thing you want to achieve in the next 5 years?", questionImposter: "Where do you see yourself next month?" },
  { question: "If you could live in any fictional world, which would it be?", questionImposter: "What fictional world do you dislike?" },
  { question: "What’s your favorite way to unwind?", questionImposter: "How do you usually relax after a long day?" },
  { question: "What’s the most surprising thing about you?", questionImposter: "What’s something people usually assume about you?" },
  { question: "If you could have any job for one week, what would it be?", questionImposter: "What job would you never want to do?" },
  { question: "What’s something you’ve never told anyone?", questionImposter: "What’s something trivial you’ve never shared?" },
  { question: "If you could invent something, what would it be?", questionImposter: "What’s a gadget you use every day?" },
  { question: "What’s one thing you want to learn but haven’t yet?", questionImposter: "What subject did you skip in school because it bored you?" },
  { question: "If you could talk to animals, which one would you talk to first?", questionImposter: "What’s an animal you are scared of?" },
  { question: "What’s your proudest achievement?", questionImposter: "What’s something you did that was just okay?" },
  { question: "If you could relive a day in your life, which day would it be?", questionImposter: "If you could skip a day, which day would you skip?" },
  { question: "What’s your biggest insecurity?", questionImposter: "What’s a quirk you have that you don’t mind?" },
  { question: "If you could fix one thing about society, what would it be?", questionImposter: "What’s one annoying thing about modern life?" },
  { question: "What motivates you to get out of bed in the morning?", questionImposter: "What’s your least favorite part of waking up?" },
  { question: "If you could speak to one deceased person, who would it be?", questionImposter: "Do you believe in an afterlife?" },
  { question: "What’s your go‑to comfort food?", questionImposter: "What snack do you always have in your kitchen?" }
,
  { question: "If you could ask your future self one question, what would it be?", questionImposter: "What’s one thing you hope happens next year?" },
  { question: "What’s your biggest pet peeve?", questionImposter: "What’s a weird habit you have?" },
  { question: "If you could time travel but only once, where would you go?", questionImposter: "If you could pause time for an hour, what would you do?" },
  { question: "What’s the one thing you’re most proud of in your life?", questionImposter: "What's something small that you're proud of?" },
  { question: "If you had to give up one sense, which would it be?", questionImposter: "Which super-sense would you most want?" },
  { question: "What’s the worst lie you’ve ever told?", questionImposter: "What’s a harmless lie you often tell?" },
  { question: "If you discovered a hidden talent, what would you hope it was?", questionImposter: "What talent do you wish you had?" },
  { question: "What’s a personality trait you admire in others?", questionImposter: "What’s a trait you dislike in yourself?" },
  { question: "If you could take a year off, what would you do?", questionImposter: "If you had one extra hour each day, what would you do?" },
  { question: "What’s something you’re bad at but enjoy anyway?", questionImposter: "What’s something you're good at but bored of?" },
  { question: "If you could trade lives with someone for a day, who would it be?", questionImposter: "Would you rather stay yourself or switch lives permanently?" },
  { question: "What’s your most vivid dream?", questionImposter: "Do you usually remember your dreams?" },
  { question: "If you could speak with your pet, what would you ask?", questionImposter: "What’s something weird your pet does?" },
  { question: "What’s a fear you've overcome?", questionImposter: "What’s a fear you still have?" },
  { question: "If you won an award, what would you want it to be for?", questionImposter: "What’s a silly award you’d want to win?" },
  { question: "What’s the kindest thing you’ve ever done?", questionImposter: "What’s something small you did for someone recently?" },
  { question: "What do you think is humanity’s greatest strength?", questionImposter: "What’s a weakness humans have?" },
  { question: "If you were a superhero, what would your name be?", questionImposter: "What’s a silly power you'd have?" },
  { question: "What’s a habit you want to build?", questionImposter: "What’s a habit you want to break?" },
  { question: "If you could see one change in the world in 10 years, what would it be?", questionImposter: "What’s something you think will never change?" }
,
  { question: "What’s your favorite tradition from your childhood?", questionImposter: "What’s a tradition your family doesn’t follow anymore?" },
  { question: "If you could instantly learn any skill, what would it be?", questionImposter: "What’s a skill you used to practice?" },
  { question: "What’s your favorite outdoor activity?", questionImposter: "What outdoor activity do you dislike?" },
  { question: "If money didn’t matter, what would your daily routine look like?", questionImposter: "What’s your routine on a normal weekday?" },
  { question: "What’s the nicest thing someone said to you recently?", questionImposter: "What’s something polite someone said to you recently?" },
  { question: "If you could choose any era to live in, which would it be?", questionImposter: "Which decade do you think was overrated?" },
  { question: "What’s something you look forward to every year?", questionImposter: "What’s something you forget about every year?" },
  { question: "If you could pick a new name for yourself, what would it be?", questionImposter: "Do you know anyone with an unusual name?" },
  { question: "What’s the best compliment someone can give you?", questionImposter: "What’s a compliment you hear often?" },
  { question: "If you could relive any moment in history, what would you pick?", questionImposter: "What’s a historical moment you never cared about?" },
  { question: "What’s your favorite thing about your personality?", questionImposter: "What’s a personality trait of yours that annoys people?" },
  { question: "What’s your favorite snack of all time?", questionImposter: "What snack do you buy the most?" },
  { question: "If you could make one rule everyone had to follow, what would it be?", questionImposter: "What’s a rule you often break?" },
  { question: "What’s one thing you wish you were better at handling?", questionImposter: "What’s something you handle well?" },
  { question: "If you could live in any movie, which one would it be?", questionImposter: "What movie do you think is overrated?" },
  { question: "What’s something you think everyone should try at least once?", questionImposter: "What’s something people try that you never will?" },
  { question: "If you could be fluent in any subject instantly, what would it be?", questionImposter: "What subject did you hate in school?" },
  { question: "What’s the most wholesome moment you've experienced?", questionImposter: "What’s a mildly funny moment you experienced?" },
  { question: "What’s your biggest goal right now?", questionImposter: "What’s something you're procrastinating?" },
  { question: "If you could create a holiday, what would it celebrate?", questionImposter: "What holiday do you forget exists?" }
,
  { question: "What’s something you wish you could unlearn?", questionImposter: "What’s something you relearned recently?" },
  { question: "If you could instantly travel anywhere right now, where would you go?", questionImposter: "Where did you last travel?" },
  { question: "What’s a talent you admire in others?", questionImposter: "What’s a talent you wish you had?" },
  { question: "If you could bring back one trend, what would it be?", questionImposter: "What trend do you think is overrated?" },
  { question: "What’s something that never fails to make you smile?", questionImposter: "What’s something that never fails to annoy you?" },
  { question: "If you could switch careers tomorrow, what would you choose?", questionImposter: "What career would you avoid?" },
  { question: "What’s one thing you think you take for granted?", questionImposter: "What’s something people accuse you of taking for granted?" },
  { question: "What’s your dream vacation?", questionImposter: "What’s a vacation you didn’t enjoy?" },
  { question: "If you could know the truth about anything, what topic would you choose?", questionImposter: "What’s something you don’t care about knowing?" },
  { question: "What’s a passion you rarely talk about?", questionImposter: "What’s a hobby you don’t care about?" },
  { question: "If you could be great at any sport, which would it be?", questionImposter: "What sport do you dislike watching?" },
  { question: "What’s the best thing you cooked or baked?", questionImposter: "What’s something you burned while cooking?" },
  { question: "If you could improve one thing about your daily routine, what would it be?", questionImposter: "What’s a routine you don’t follow anymore?" },
  { question: "What’s a song that means a lot to you?", questionImposter: "What’s a song you’re tired of hearing?" },
  { question: "If you could instantly upgrade one part of your life, what would it be?", questionImposter: "What’s something you think is fine the way it is?" },
  { question: "What’s your favorite thing to learn about?", questionImposter: "What’s something you recently learned by accident?" },
  { question: "If you could have any animal as a pet, real or fictional, what would it be?", questionImposter: "What’s a pet you’d never want?" },
  { question: "What’s something you always recommend to others?", questionImposter: "What’s something others recommend to you that you ignore?" },
  { question: "If you had a personal assistant, what would you have them do?", questionImposter: "What’s a chore you never procrastinate?" },
  { question: "What’s a small thing that changed your life?", questionImposter: "What’s a small thing that didn’t matter to you?" }
,
  { question: "If you could relive one conversation, which would it be?", questionImposter: "What’s a conversation you barely remember?" },
  { question: "What’s something you wish people celebrated more?", questionImposter: "What’s a celebration you forget about?" },
  { question: "If you could experience one moment again for the first time, what would it be?", questionImposter: "What’s a moment you don’t remember well?" },
  { question: "What’s the most meaningful compliment someone gave you?", questionImposter: "What’s a compliment you hear frequently?" },
  { question: "If you could make one thing easier for everyone, what would it be?", questionImposter: "What’s something people complain about often?" },
  { question: "What’s a view or scenery you’ll never forget?", questionImposter: "What scenery do you find boring?" },
  { question: "If you could try any job for one day, what would it be?", questionImposter: "What job would you never apply for?" },
  { question: "What’s something that instantly puts you in a good mood?", questionImposter: "What’s something that instantly irritates you?" },
  { question: "If you could teleport anywhere for lunch, where would you go?", questionImposter: "Where did you last eat out?" },
  { question: "What’s the nicest gift you’ve ever given someone?", questionImposter: "What’s a gift you gave that didn’t matter much?" },
  { question: "If you could learn one dangerous skill safely, what would it be?", questionImposter: "What’s a dangerous skill you’d never try?" },
  { question: "What’s a personality trait you developed over time?", questionImposter: "What’s a trait you had since childhood?" },
  { question: "If you could have a perfect day, what would it look like?", questionImposter: "What’s a typical day for you?" },
  { question: "What’s something you admire about your parents?", questionImposter: "What’s something your parents do that annoys you?" },
  { question: "If you could erase one worry from your life, what would it be?", questionImposter: "What’s something you rarely worry about?" },
  { question: "What’s the best thing you learned this year?", questionImposter: "What’s something you learned a long time ago?" },
  { question: "If you could change one rule in society, what would it be?", questionImposter: "What’s a rule you ignore sometimes?" },
  { question: "What’s something you think is underrated?", questionImposter: "What’s something you think is overrated?" },
  { question: "If you could have any artist paint your portrait, who would it be?", questionImposter: "What’s an art style you dislike?" },
  { question: "What’s a tradition you want to start one day?", questionImposter: "What’s a tradition you don’t care about?" }
];
