const questionPairs = [
  { question: "What would you tell your 10 year old self if you can travel back in time?", questionImposter: "What advice would you give a dog if you could talk to him?" },
  { question: "How many yards do you think you can run after receiving an NFL kickoff?", questionImposter: "How many yards would you want your boat to be long?" },
  { question: "How many dates before kissing?", questionImposter: "Pick a number between 5 and 10." },
  { question: "If you could see any artist in concert who would it be?", questionImposter: "Best concert you've been to?" },
  { question: "How much should you spend on a car?", questionImposter: "How much does a brand new car cost?" },
  { question: "What item in your house you can’t live without?", questionImposter: "What's the most fragile thing in your house." },
  { question: "Best age to start puberty?", questionImposter: "Pick a number from 9 to 15." },
  { question: "What answer do you want to listen more of?", questionImposter: "Which singer sings 'Umbrella'?" },
  { question: "Who is the most responsible in the group (currently playing)?", questionImposter: "Name a person who is currently playing the game." },
  { question: "Who’d you call first if you won the lottery?", questionImposter: "Out of the players currently playing who would you trust the most with a secret?" },
  { question: "How much $ would it take to reveal your Internet search history?", questionImposter: "Pick an amount of money from 1mil to 10mil (round numbers)?" },
  { question: "How many hours of sleep do you get per night", questionImposter: "How would you rate your sleep (1-10)?" },
  { question: "How many alarms do you set to wake up?", questionImposter: "Pick a number between 5 and 15?" },
  { question: "How long could you survive in the woods?", questionImposter: "Pick a time interval (30 days to 1 year, don't be too specific)." },
  { question: "What animal's ability would you want to have?", questionImposter: "What animal are you irrationally afraid of?" },
  { question: "What is the best country to party in?", questionImposter: "Which country would you want to live in?" },
  { question: "Which country has the best cuisine?", questionImposter: "Which country has the worst cuisine?" },
  { question: "Who from the group (currently playing) would make the best lawyer?", questionImposter: "Who from the group (currently playing) would make the best doctor?" },
  { question: "Meme that you quote often?", questionImposter: "Name an Italian brainrot character." },
  { question: "What age did you get your first phone?", questionImposter: "At what age would you let your kid get a phone?" },
  { question: "What celebrity would you like to have a dinner with?", questionImposter: "Most attractive female actor?" },
  { question: "What would you show a medieval peasant?", questionImposter: "What piece of modern technology could you not live without?" },
  { question: "What would you show people from the future to represent 2025?", questionImposter: "Favorite TV show / movie of the year?" }
,
  { question: "What’s your ideal weekend activity?", questionImposter: "What’s something you usually do on a random Tuesday?" },
  { question: "What food could you eat every day without getting tired of it?", questionImposter: "What food have you eaten recently?" },
  { question: "What hobby would you pick up if you had unlimited free time?", questionImposter: "What hobby did you used to have as a kid?" },
  { question: "What’s one irrational fear you have?", questionImposter: "What’s something that annoys you for no reason?" },
  { question: "What season fits your personality best?", questionImposter: "What season do you dislike the most?" },
  { question: "Which movie universe would you want to live in?", questionImposter: "What’s the last movie you watched?" },
  { question: "What’s your favorite type of weather?", questionImposter: "What kind of weather ruins your plans?" },
  { question: "If you could instantly master a skill, which one would it be?", questionImposter: "Which skill do you wish you were slightly better at?" },
  { question: "What’s the best compliment you’ve ever received?", questionImposter: "What compliment do you usually give others?" },
  { question: "If you could only keep one app on your phone, what would it be?", questionImposter: "What app do you use the least?" },
  { question: "What fictional character do you relate to the most?", questionImposter: "What fictional character do you find annoying?" },
  { question: "What’s your favorite beverage of all time?", questionImposter: "What did you drink today?" },
  { question: "If you had to switch jobs for a month, what job would you choose?", questionImposter: "What job could you never imagine doing?" },
  { question: "What’s something you wish you learned earlier in life?", questionImposter: "What's something you're planning to learn soon?" },
  { question: "What’s your comfort movie or show?", questionImposter: "Which movie or show have you disliked recently?" },
  { question: "If you could speak any language fluently, which would it be?", questionImposter: "Which language do you think is hardest to learn?" },
  { question: "What holiday do you look forward to the most?", questionImposter: "What holiday do you celebrate the least?" },
  { question: "What smell instantly puts you in a good mood?", questionImposter: "What smell do you really hate?" },
  { question: "What is your favorite childhood memory?", questionImposter: "What's something funny you did as a kid?" },
  { question: "If you could have dinner anywhere in the world tonight, where would you go?", questionImposter: "What’s the best meal you’ve eaten this year?" }
];
